/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: "category",
      label: "1. Java & JVM",
      items: [{ type: "autogenerated", dirName: "01-java-jvm" }],
    },
    {
      type: "category",
      label: "2. DBMS",
      items: [{ type: "autogenerated", dirName: "02-dbms" }],
    },
    {
      type: "category",
      label: "3. Spring Boot",
      items: [{ type: "autogenerated", dirName: "03-spring-boot" }],
    },
    {
      type: "category",
      label: "4. OS",
      items: [{ type: "autogenerated", dirName: "04-os" }],
    },
    {
      type: "category",
      label: "5. Networks",
      items: [{ type: "autogenerated", dirName: "05-networks" }],
    },
    {
      type: "category",
      label: "6. Security",
      items: [{ type: "autogenerated", dirName: "06-security" }],
    },
    {
      type: "category",
      label: "7. Cross Cutting",
      items: [{ type: "autogenerated", dirName: "07-cross-cutting" }],
    },
    {
      type: "category",
      label: "8. Distributed Sys",
      items: [{ type: "autogenerated", dirName: "08-distributed-systems" }],
    },
    {
      type: "category",
      label: "9. Caching",
      items: [{ type: "autogenerated", dirName: "09-caching" }],
    },
    {
      type: "category",
      label: "10. Message Queues",
      items: [{ type: "autogenerated", dirName: "10-message-queues" }],
    },
    {
      type: "category",
      label: "11. Microservices",
      items: [{ type: "autogenerated", dirName: "11-microservices" }],
    },
    {
      type: "category",
      label: "12. API Design",
      items: [{ type: "autogenerated", dirName: "12-api-design" }],
    },
    {
      type: "category",
      label: "13. Testing",
      items: [{ type: "autogenerated", dirName: "13-testing" }],
    },
    {
      type: "category",
      label: "14. CI/CD",
      items: [{ type: "autogenerated", dirName: "14-cicd-devops" }],
    },
    {
      type: "category",
      label: "15. Java 8+",
      items: [{ type: "autogenerated", dirName: "15-java-features" }],
    },
    {
      type: "category",
      label: "16. LLD",
      items: [{ type: "autogenerated", dirName: "16-lld" }],
    },
    {
      type: "category",
      label: "17. HLD",
      items: [{ type: "autogenerated", dirName: "17-hld" }],
    },
  ],
};

module.exports = sidebars;
