const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar slice from the docs folder (or versioned_docs/<version>)
    },
  ],
};

module.exports = sidebars;
